spring.application.name=prueba
server.port=8080
spring.datasource.url=${SUPABASE_JDBC_URL:jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USER:postgres.yulrthrlmezbyvvrgeuh}
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
app.security.jwt-secret=${APP_JWT_SECRET}
